don't base64-encode html as plain text
bellroy/wai-handler-hal pull request #26
Opened 2023-12-13 14:19 UTC by jaspervdj

I have an application running for the ZuriHac registration that used my own hacked-together lambda runtime -- I think `hal` didn't exist at the time.

I am in the process of porting this to `hal`, and found that I can't get plain HTML pages to render in the browser, they come out as base64-encoded versions.

Adding this Content-Type fixed it, but I wonder if we should not have the entirety of `text/` as a prefix?

2023-12-13 22:27 UTC, JackKelly-Bellroy commented
> I wonder if we should not have the entirety of `text/` as a prefix?

I think you might be right. I'm also not sure why that's doing a `T.isPrefixOf` check. It might have been a misguided attempt to capture MIME types which denote responses in a particular format, but actually those are suffixed with things like `+json` (e.g., `application/problem+json`).

How does this sound: avoid base64-encoding the response when any of the following are true of the content-type:

* starts with `text/`
* is `application/json`
* ends with `+json`
* ends with `+xml`

What do you think? Also, would you mind adding a CHANGELOG.md entry?

2023-12-13 23:04 UTC, lrworth commented
What about `application/xml`? It might be better to make the decision function user-configurable with a reasonable default, since it seems impossible for wai-handler-hal to make this decision for every possible MIME type.

2023-12-13 23:39 UTC, JackKelly-Bellroy commented
Yes, we should support `application/xml` too, as part of the sensible default.

@jaspervdj which way do you want to take this? If you want to get your change out ASAP so you can keep building ZuriHac stuff, then we'll do that and move the broader MIME type discussion to another issue.

2023-12-14 08:00 UTC, jaspervdj commented
> @jaspervdj which way do you want to take this? If you want to get your change out ASAP

No hurry on my part; I already pinned the commit where I added `text/html` in our project so I'm not blocked on this at all.

Making this user-configurable with a good default seems like the right direction to me.

I guess a function `Text -> Bool` is nicer than a list of prefixes and suffixes?

2023-12-14 08:17 UTC, JackKelly-Bellroy commented
All right, then let's take in a `Text -> Bool` parameter. I think we probably want to collect the new predicate and the existing `Vault` and `PortNumber` arguments to `runWithContext` all into an options record, and provide a default value for that record. That keeps `run` as the common-case simple interface, and `runWithContext` has all the necessary knobs.

2023-12-14 09:49 UTC, jaspervdj commented
I added this change, including a test.  Unfortunately this is a breaking change, but I guess at least the `Options` datatype can now be extended more easily...

2023-12-14 22:40 UTC, JackKelly-Bellroy requested changes
Most of these are pretty trivial, and I look forward to merging and releasing it ASAP.

2023-12-14 22:40 UTC, JackKelly-Bellroy commented on wai-handler-hal.cabal
> +    , tasty-hunit      ^>=0.9
If `tasty-hunit ^>=0.10` also works, can you please widen these bounds?

2023-12-14 22:40 UTC, JackKelly-Bellroy commented on test/Network/Wai/Handler/HalTest.hs
> +test_DefaultBinaryMimeTypes = testCase "default binary MIME types" $ do
We generally format our code with `ormolu`, which will sadly wreck this nice layout. Can you please reformat? You might like to make a list of tuples if you think that makes a better layout.

2023-12-14 22:40 UTC, JackKelly-Bellroy commented on wai-handler-hal.cabal
Please update the package version and write a `CHANGELOG.md` entry — I'll do a release after we get this merged.

2023-12-14 22:40 UTC, JackKelly-Bellroy commented on src/Network/Wai/Handler/Hal.hs
> +    optionsVault :: Vault
Can you please drop the prefix on the record selectors? I think it's unlikely we'll hit too many name clashes, and modern extensions and libraries make un-prefixed fields fairly nice to work with.

2023-12-14 22:40 UTC, JackKelly-Bellroy commented on src/Network/Wai/Handler/Hal.hs
> +-- 'defaultOptions' provides sensible defaults.
Thank you for good haddocks all through this PR.

2023-12-14 22:40 UTC, JackKelly-Bellroy commented on src/Network/Wai/Handler/Hal.hs
> +  -- | Configuration options, 'defaultOptions' provides sensible defaults.
```suggestion
  -- | Configuration options. 'defaultOptions' provides sensible defaults.
```

2023-12-14 22:40 UTC, JackKelly-Bellroy commented on src/Network/Wai/Handler/Hal.hs
>      runWithContext,
I would prefer if we used the following order in the export list and when declaring these types and functions within the module:
```suggestion
    runWithContext,
    Options (..),
    defaultOptions,
```
Reason: The reader is then presented with the two main entry points to the module, and then the "what's an `Options`, and how do I make one?" is immediately raised and answered.

2023-12-15 09:04 UTC, JackKelly-Bellroy commented on wai-handler-hal.cabal
> +    , tasty-hunit      >=0.9
```suggestion
    , tasty-hunit      >=0.9 && <0.11
```
(and then `cabal-fmt`)

2023-12-15 09:09 UTC, jaspervdj commented
Thanks for the feedback!  I think I pushed all the requested changes.  Let me know if you want me to squash everything into one commit or set a concrete version release date (I put UNRELEASED for now).

2023-12-15 09:25 UTC, JackKelly-Bellroy approved these changes
Thanks very much. Please set the release date to 2023-12-16; I'll have some time tomorrow morning to push the release to Hackage. I'm happy to use GH's squash-merge feature on this PR, so don't worry about doing that.

2023-12-17 02:36 UTC, merged

2023-12-17 03:15 UTC, JackKelly-Bellroy commented
Released as 0.3.0.0. Thanks for the PR.